---
- name: Add support NFS
  become: true
  ansible.builtin.apt:
    name: nfs-kernel-server

- name: Create exports folder
  become: true
  ansible.builtin.file:
    path: /etc/exports.d
    state: directory
    mode: "0755"

- name: Copy exports file
  become: true
  ansible.builtin.template:
    src: nfs.exports.j2
    dest: /etc/exports.d/nfs.exports
    mode: "0644"
  notify: Restart NFS service

- name: Enable and start NFS service
  become: true
  ansible.builtin.systemd:
    name: nfs-server
    enabled: true
    state: started
