---
### Ansible

username: raspberry
ip: 192.168.1.251
ssh:
  key: ~/.ssh/servers
  port: 22

ansible_host: "{{ ip }}"
ansible_user: "{{ username }}"
ansible_connection: ssh
ansible_port: "{{ ssh.port }}"
ansible_ssh_private_key_file: "{{ ssh.key }}"

### Hostname

hostname: pi

### Access

wireless:
  ssid: "{{ vault_wireless.ssid }}"
  country_code: FR
  interface: wlan0
  hw_mode: g # a = 5 Ghz and g = 2.4 Ghz
  channel: 6 # 6 for 2.4 GHz, 48 for 5 GHz, 0 for auto
  # Note: you can list the available frequencies with this: sudo iw list
  wpa:
    version: 2 # 1=wpa only, 2=wpa2 only, 3=both
    passphrase: "{{ vault_wireless.passphrase }}"
    key_mgmt: WPA-PSK # sets wpa key management
    pairwise: TKIP # sets encryption used by WPA
    rsn_pairwise: CCMP # sets encryption used by WPA2
  macaddr_acl: 0 # 0 means "accept unless in deny list"
  auth_algs: 1 # 1=wpa, 2=wep, 3=both
  ignore_broadcast_ssid: 0 # setting ignore_broadcast_ssid to 1 will disable the broadcasting of ssid
  wmm_enabled: 1 # QoS support, also required for full speed on 802.11n/ac/ax
  driver: nl80211
  ieee80211:
    - "ieee80211d=1" # limit the frequencies used to those allowed in the country
    - "ieee80211n=1" # 802.11n (Wi-Fi 4) support
    # - "ieee80211ac=1" # 802.11ac (Wi-Fi 5) support

ethernet_interface: eth0

bridge_interface: br0

### Samba

samba:
  public:
    share: /media/public/nas

### Jellyfin

jellyfin_media_root: "{{ samba.public.share }}/media"
